- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Add user to docker group
  user:
    name: ubuntu
    groups: docker
    append: yes

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
- name: Install Python Docker SDK for Ansible
  pip:
    name: docker
    executable: pip3

- name: Ensure pip3 is installed
  apt:
    name: python3-pip
    state: present
